// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _bigIRT_item_info_accum_cpp_impl(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_laplace_ability_beta_rows_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_laplace_corr_grad_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_laplace_direct_block_fg_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_laplace_item_block_objective_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_laplace_item_eval_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_laplace_item_objective_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_laplace_person_beta_fused_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_laplace_person_beta_grouped_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_laplace_person_row_terms_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_laplace_person_step_block_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_person_covariance_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_person_sigma_points_cpp_dense_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_person_sigma_points_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _bigIRT_row_aSa_cpp_impl(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _rcpp_module_boot_stan_fit4irt_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4irt_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4irt_mod, 0},
    {"_bigIRT_item_info_accum_cpp_impl",              (DL_FUNC) &_bigIRT_item_info_accum_cpp_impl,               4},
    {"_bigIRT_laplace_ability_beta_rows_cpp_impl",    (DL_FUNC) &_bigIRT_laplace_ability_beta_rows_cpp_impl,    13},
    {"_bigIRT_laplace_corr_grad_cpp_impl",            (DL_FUNC) &_bigIRT_laplace_corr_grad_cpp_impl,             9},
    {"_bigIRT_laplace_direct_block_fg_cpp_impl",      (DL_FUNC) &_bigIRT_laplace_direct_block_fg_cpp_impl,      41},
    {"_bigIRT_laplace_item_block_objective_cpp_impl", (DL_FUNC) &_bigIRT_laplace_item_block_objective_cpp_impl, 34},
    {"_bigIRT_laplace_item_eval_cpp_impl",            (DL_FUNC) &_bigIRT_laplace_item_eval_cpp_impl,            12},
    {"_bigIRT_laplace_item_objective_cpp_impl",       (DL_FUNC) &_bigIRT_laplace_item_objective_cpp_impl,       11},
    {"_bigIRT_laplace_person_beta_fused_cpp_impl",    (DL_FUNC) &_bigIRT_laplace_person_beta_fused_cpp_impl,    13},
    {"_bigIRT_laplace_person_beta_grouped_cpp_impl",  (DL_FUNC) &_bigIRT_laplace_person_beta_grouped_cpp_impl,  14},
    {"_bigIRT_laplace_person_row_terms_cpp_impl",     (DL_FUNC) &_bigIRT_laplace_person_row_terms_cpp_impl,      9},
    {"_bigIRT_laplace_person_step_block_cpp_impl",    (DL_FUNC) &_bigIRT_laplace_person_step_block_cpp_impl,    40},
    {"_bigIRT_person_covariance_cpp_impl",            (DL_FUNC) &_bigIRT_person_covariance_cpp_impl,            12},
    {"_bigIRT_person_sigma_points_cpp_dense_impl",    (DL_FUNC) &_bigIRT_person_sigma_points_cpp_dense_impl,    10},
    {"_bigIRT_person_sigma_points_cpp_impl",          (DL_FUNC) &_bigIRT_person_sigma_points_cpp_impl,          12},
    {"_bigIRT_row_aSa_cpp_impl",                      (DL_FUNC) &_bigIRT_row_aSa_cpp_impl,                       5},
    {NULL, NULL, 0}
};

RcppExport void R_init_bigIRT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
