# # Generated by rstantools.  Do not edit by hand.
#
# # names of stan models
# stanmodels <- c("irt")
#
# # load each stan module
# Rcpp::loadModule("stan_fit4irt_mod", what = TRUE)
#
# # instantiate each stanmodel object
# stanmodels <- sapply(stanmodels, function(model_name) {
#   # create C++ code for stan model
#   stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
#   stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
#   stanfit <- rstan::stanc_builder(stan_file,
#                                   allow_undefined = TRUE,
#                                   obfuscate_model_name = FALSE)
#   stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
#                             model_cppcode = stanfit$cppcode)
#   # create stanmodel object
#   methods::new(Class = "stanmodel",
#                model_name = stanfit$model_name,
#                model_code = stanfit$model_code,
#                model_cpp = stanfit$model_cpp,
#                mk_cppmodule = function(x) get(paste0("model_", model_name)))
# })
#
#
#


#modified, from ctsem

MODELS_HOME <- "src"
if (!file.exists(MODELS_HOME)) MODELS_HOME <- sub("R$", "src", getwd())

w32 <-  (.Platform$OS.type=="windows" && .Platform$r_arch=="i386")#.Machine$sizeof.pointer == 4 && .Platform$OS.type == "windows" #&&

stan_files <- dir(file.path(MODELS_HOME, paste0('stan_files',ifelse(w32,'32',''))),
  pattern = "stan$", full.names = TRUE)
stanmodels <- lapply(stan_files, function(f) {
  model_cppname <- sub("\\.stan$", "", basename(f))
  stanfit <- suppressWarnings(rstan::stanc(f, allow_undefined = TRUE,
    obfuscate_model_name = FALSE))
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
    model_cppcode = stanfit$cppcode)
  sm <- do.call(methods::new, args = c(stanfit[-(1:3)],
    Class = c("stanmodel"),#,),
    mk_cppmodule = function(x) get(paste0("model_", model_cppname))))
  #attributes(sm)StanHeaders <- packageDescription('StanHeaders')$version
  return(sm)
}
)
names(stanmodels) <- sub("\\.stan$", "", basename(stan_files))
rm(MODELS_HOME)
rm(w32)
